server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: 192.168.50.160:9092,192.168.50.160:9093,192.168.50.160:9096
    producer: #???
      retries: 3 #????0????????????????????
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: default-group1
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      # ??????????????ListenerConsumer???????
      # RECORD
      # ???poll()???????????ListenerConsumer???????
      # BATCH
      # ???poll()???????????ListenerConsumer?????????????????TIME???
      # TIME
      # ???poll()???????????ListenerConsumer?????????record??????count???
      # COUNT
      # TIME | COUNT??????????
      # COUNT_TIME
      # ???poll()???????????ListenerConsumer??????????Acknowledgment.acknowledge()???
      # MANUAL
      # ????Acknowledgment.acknowledge()?????
      # MANUAL_IMMEDIATE
      ack-mode: manual_immediate

